### ISSUE TITLE
[Kitten] Revoir le `is-selected` pour le combo `RadioButton` + `TagButton`

### ISSUE THREAD

**Issue by LanF3usT** [KissKissBankBank/kitten#1028]
## Objectif

Il faudrait appliquer des styles pour le `selected` sur `TagButton` quand le `RadioButton` est sélectionné.

## Screenshot

<img width="140" alt="capture d ecran 2018-01-09 a 12 25 28" src="https://user-images.githubusercontent.com/736319/34719479-50cf9512-f53b-11e7-990a-47b474717b01.png">

**Comment by lorrN** [comment]
@LanF3usT est ce toujours d'actualité ?
