### ISSUE TITLE
Project Cards background

### ISSUE THREAD

**Issue by sunny** [KissKissBankBank/kitten#1130]
Pendant le chargement des images, sous Firefox, le texte alternatif apparaît sur l'image.

<img width="695" alt="image" src="https://user-images.githubusercontent.com/132/38031102-bf8e7f94-329a-11e8-92a9-b52f074267a4.png">

Est-ce qu'on pourrait améliorer ce style ? A minima on pourrait ajouter une couleur de texte plus grise et centrer ce texte, par exemple :

<img width="690" alt="image" src="https://user-images.githubusercontent.com/132/38031049-9b4b5d0a-329a-11e8-85d0-217218487461.png">

Aussi, afin de pouvoir [afficher la couleur dominante en fond](https://github.com/sunny/carrierwave-color#using-your-dominant-color), est-ce qu'on pourrait avoir une prop qui permettrait de changer la couleur de fond de l'image ?

**Comment by Morgan-jarry** [comment]
Pour faire comme sur `cults` \o/ Bonne idée !
