### ISSUE TITLE
[Stability] Supprimer le module kitten-launcher

### ISSUE THREAD

**Issue by LanF3usT** [KissKissBankBank/kitten#1147]
À voir mais j'ai l'impression qu'on ne se sert plus vraiment de ce module et qu'on ne le met pas forcément à jour avec des nouveaux modules. Pour que ce soit plus clair, et qu'on ne cherche pas de qui ajoute quel module, je propose qu'on migre tout dans `kitten-components`.

@KissKissBankBank/tech-front Qu'en pensez-vous ?

**Comment by Ynote** [comment]
Le but de `kitten-launcher` était de permettre plus facilement l'installation de `kitten-components` sur chacune des plateformes. Mais, c'était une fausse bonne idée : 
- ça empêche de voir clairement les dépendances,
- chaque plateforme avance à son rythme et la mise à jour des dépendances devrait se faire dessus.

Du coup, je plussoie cette suppression. Mais, ce n'est pas dans `kitten-components` qu'il faut migrer les dépendances mais sur chacune des apps.  Je vais voir si je peux faire ça dans la foulée du clean de la gem sur KissKiss.
