### ISSUE TITLE
[Cleaning] Séparer le module npm de la structure de l'engine Rails

### ISSUE THREAD

**Issue by Ynote** [KissKissBankBank/kitten#1156]
Pour préparer une séparation possible du module npm Kitten et du styleguide, je propose de ranger tous les assets du module dans un dossier `node_package` à la racine du repo : 
```
|- app
|- bin
|- config
…
|- node_package
   |- src
   |   |- index.js // le point d'entrée du package.json
   |   |- kitten
   |       |- components
   |       |- config
   |       |- constants
   |       |- handlers
   |       |- helpers
   |       |- hoc
   |       |- karl // à migrer dans spec/dummy plus tard
   |
   |- dist // la PR de build de Bastien
```

Je suis encore en train de creuser, pour d'éventuelles conséquences sur KissKiss, LENDO et le styleguide (et hellomerci…), mais pour l'instant, j'ai listé que cela nécessiterait : 
- [ ] Créer le dossier `node_package` et migrer tous les dossiers de `assets/javascripts`
- [ ] Mettre à jour tous les paths dans le `package.json`

Cela ne devrait pas provoquer de breaking change et nous permettrait ensuite d'avoir une vision plus claire. À terme, on on pourra exporter un module `Kitten` qui expose tous les composants que l'on souhaite au lieu d'exposer des chemins.

**Comment by LanF3usT** [comment]
Que penses-tu de placer le `index.js` à la racine de `node_package` ?
