### ISSUE TITLE
Mettre en place ESlint afin d'avoir une liste de règles de développement permettant de s'assurer de la qualité des composants

### ISSUE THREAD

**Issue by FlorentD** [KissKissBankBank/kitten#1352]
Définir et mettre en places des règles ESlint (https://eslint.org/docs/rules/) pour s'assurer que les composants soient de qualité au niveau JS et React.

Il faudra trouver le bon équilibre entre souplesse et rigueur.

Il faudra mettre en place un hook pour empêcher de commit si le code produit ne respecte pas les règles.

**Comment by joachimesque** [comment]
#1973
