### ISSUE TITLE
[Tech] Étudier une alternative à Radium

### ISSUE THREAD

**Issue by LanF3usT** [KissKissBankBank/kitten#1416]
Depuis le début de l'utilisation de `Radium` sur Kitten, nous avons connu pas mal de soucis en terme d'implémentation, de fails au niveau de la librairie, de problèmes liés au HOC (state qui casse), etc, etc…

Ca peut être intéressant de tester d'autres librairies. https://www.styled-components.com/ me semble pas trop mal sur le papier.

**Comment by LanF3usT** [comment]
## TODO

- [ ] Usage
- [ ] Auto-prefixe
- [ ] Media-queries
- [ ] Pseudo classes
- [ ] Animations (Keyframe, …)
- [ ] Performance

**Comment by Ynote** [comment]
Pour les pseudo-classes, ça peut être intéressant de faire la différence entre : 
- `:hover`, `:focus`, etc. (qui sont gérés avec des `onMouseEnter`, `onFocus`, etc)
- `:first-child`, `:last-child`, etc.

Je pense que le second type de pseudo est rarement géré (ou que ça serait peut-être gourmand en perf ?).

**Comment by LanF3usT** [comment]
Pour les `first-child`, c'est en effet mieux de gérer cela en JS avec des merges de styles (à creuser tout de même au niveau perf). Pour les `pseudo-classes` d'état, la gestion en CSS me parait plus pertinente et évite la gestion d'un état interne au niveau du composant React.

**Comment by LanF3usT** [comment]
`styled-components` gère tout cela via des classes. Ca conserve la puissance du CSS du coup.

**Comment by Ynote** [comment]
BOUYA 🎉

**Comment by camilledel** [comment]
`export const FooBar = styled.div`` ajoute les styles sur toutes les `div` du composant `FooBar` ? Comment tu fais quand tu as plusieurs `div` dans un même composant ?
@LanF3usT

**Comment by LanF3usT** [comment]
`styled.div` créé un composant avec une `div`. Dans le cas de plusieurs divs, il faut faire plusieurs composants qui auront leurs propres styles.

Exemple pour un composant avec un titre et 2 boutons :
```js
const Button = styled.button`…`
const Title = styled.h1`…`

const FooBar = () => (
  <>
    <Title>MyTitle</Title> // <h1 class="4242">MyTitle</h1>
    <Button>MyPrimaryButton</Button> // <button class="9999">MyPrimaryButton</button>
    <Button>MySecondaryButton</Button> // <button class="9999">MySecondaryButton</button>
  </>
)
```

**Comment by camilledel** [comment]
Yes du coup j'ai lu la doc ! Mais cette façon de hiérarchiser quasi tous les composants avec leurs propres styles en récréant un autre nom de composant ne va pas aider à la compréhension du composant général, non ?
