### ISSUE TITLE
[Kitten] Styleguide VS Storybook

### ISSUE THREAD

**Issue by qsvr** [KissKissBankBank/kitten#1428]
Public VS pas public ?
Nouvelle version allégée si public ?

Ressources nécessaire pour kitten + storybook : 
- 1 temps plein pour tout refaire : temps long
- MAJ régulières pour ajout de nouveaux composants ou répercussion des changements de charte sur les composants existants

**Comment by camilledel** [comment]
Coté intégration à chaque modifs ou création de composants nous devons : 

- écrire des tests
- intégrer le composant sur storybook
- intégrer le composant sur le styleguide

**Comment by joachimesque** [comment]
#1575
