### ISSUE TITLE
[Grid] Ajouter une prop `cols`

### ISSUE THREAD

**Issue by LanF3usT** [KissKissBankBank/kitten#1542]
Pour pouvoir gérer au mieux les grilles dans des grilles, il peut être intéressant d'ajouter une prop pour lui spécifier d'avoir que 6 colonnes par exemple.

```js
<Grid /> // Divise le container par 12 (valeur par défaut).
<Grid cols="6" /> // Divise le container par 6.
```

**Comment by joachimesque** [comment]
#1598
