### ISSUE TITLE
Gestion des bordures sur k-TabBar et k-HorizontalNav

### ISSUE THREAD

**Issue by Ynote** [KissKissBankBank/kitten#167]
Suite à #166 et #165, afin de pouvoir avoir des bordures de plus de 1px sur les items sélectionnés, il n'est plus possible d'avoir une couleur de fond sur ces composants de navigation.

Nous pourrions gérer cela avec un niveau de DOM en plus. Avoir les `<li />` qui auront des bordures transparentes pour simuler les états non-sélectionnés.

**Comment by Ynote** [comment]
@LanF3usT à ton avis, est-ce qu'on ferme cette issue ? Sachant qu'on va essayer de faire un autre composant ressemblant à `k-HorizontalNav` pour la page projet Lendo et le formulaire sur le dépôtoir ?

**Comment by LanF3usT** [comment]
Oui on peut la fermer.
