### ISSUE TITLE
Mettre à jour la version de `react-select`

### ISSUE THREAD

**Issue by Morgan-jarry** [KissKissBankBank/kitten#1853]
# Description du problème

L'utilisation actuelle du composant `Select` de kitten génère une erreur en console :

![image](https://user-images.githubusercontent.com/523306/69143538-825c1b00-0ac9-11ea-8fe1-4dabc26439db.png)
Le composant en question utilise la librairie `react-select`.

# Résultat attendu

[Mettre à jour la version de `react-select`](https://react-select.com/upgrade-guide#upgrade-guide) et appliquer les modifications au composant React `Select`, s'il y a lieu, afin que le composant fonctionne dans cette nouvelle version et reste compatible sur les plateformes de Lendo et KissKiss.

**Comment by joachimesque** [comment]
#2211
