### ISSUE TITLE
[Stability] Suppression de Radium

### ISSUE THREAD

**Issue by LanF3usT** [KissKissBankBank/kitten#1894]
## Objectifs

Cette PR a pour objectif de supprimer la dépendance de Kitten à la librairie `Radium` au profit de l'utilisation de `styled-components`. Pour se faire, voici la liste des composants qui utilisent actuellement `Radium`.

Dans l'idéal, on peut en profiter pour restructurer le composant, ajouter des tests via le système de snaps et ajouter une/des stories.

```
/nom_du_composant
  /components
    - sous_composant.js
  - index.js
  - stories.js
  - test.js
```

## Liste des composants

- [x] LinkBox https://github.com/KissKissBankBank/kitten/pull/1895
- [x] ButtonImageWithText https://github.com/KissKissBankBank/kitten/pull/1897
- [x] ButtonImageWithText (stories) https://github.com/KissKissBankBank/kitten/pull/1897
- [X] CartRewardCard #2056
- RewardCard
  - [x] RewardCardButton #2060
  - [x] RewardCardCheckedIconLine #2060
  - [x] RewardCardCheckedIcon #2060
  - [x] RewardCardContent #2060
  - [x] RewardCardImage #2060
  - [x] Info #2060
  - [x] RewardCardInfos #2060
  - [x] LegacyRewardCardContainer #2060
  - [x] ManageContributionBase #2060
  - [x] RewardCardRowSide #2060
  - [x] RewardCardTitle #2060
- [X] TeamCardButtonWithTooltip #2052
- [X] TeamCardIcons #2052
- [X] TeamCardImage #2052
- [X] TeamCardPhoneIcon #2052
- [X] Triptych #2053
- [X] VerticalCardWithAction  #2054
- Carousel 
  - [x] CarouselInner #2066
  - [x] CarouselPage #2066
  - [x] CarouselSection #2066
  - [x] Carousel #2066
- [x] Expandable (stories) #2055
- [x] Checkbox (stories) #2055
- [X] LegoGrid #2058
- [X] Hero #2059
- [X] Hero (stories) #2059
- [x] ArrowIcon
- [X] Timeline #2057
- [x] EmbedPlayer
- [x] EmbedPlayer (stories)
- [x] CounterBlock
- [x] KarlButtonIconFilter  #2067
- [x] KarlButtonImageWithText #2055
- [x] KarlGarbageButtonComponent #2055
- [x] KarlRewardCard #2060
- [x] RewardCard (stories) #2060
- [x] KarlVerticalCardWithAction #2055
- [x] KarlVerticalCard #2055
- [x] KarlFooterKisskiss  #2067
- [x] KarlFooterLendo  #2067
- [x] KarlCommentForm #2055
- [x] KarlComment #2055
- [X] KarlHeroExamples #2059
- [x] KarlHorizontalStrokes #2055
- [x] KarlPaginationExamples #2055
- [x] KarlIconBadge #2055
- [x] ProjectsCarousel #2066
- PreDeposit
  - [x] HeaderWithBackground #2062
  - [x] KeySection #2062
  - [x] PartnersSection #2062
  - [x] PreDeposit #2062
  - [x] TimelineSection #2062
  - [x] TipSimpleCarousel #2062
  - [x] TipsSection #2062
  - [x] CardWithButton #2062 
  - [X] SolutionsTriptych #2053 +  #2062
- [x] SimpleTemplate #2061

**Comment by joachimesque** [comment]
Point d’avancement du Clean Radium : https://github.com/KissKissBankBank/kitten/issues/1894

11 PR ont été ouvertes :

- [RemoveRadium] Remove from `TeamCard` https://github.com/KissKissBankBank/kitten/pull/2052 :white_check_mark:
- [RemoveRadium] Remove from `Triptych` https://github.com/KissKissBankBank/kitten/pull/2053 :white_check_mark:
- [RemoveRadium] Remove Radium from `VerticalCardWithAction` https://github.com/KissKissBankBank/kitten/pull/2054
- [RemoveRadium] Remove from various (easy) stories and Karl components https://github.com/KissKissBankBank/kitten/pull/2055 :white_check_mark:
- [RemoveRadium] Remove from `CartRewardCard` https://github.com/KissKissBankBank/kitten/pull/2056
- [RemoveRadium] Remove from `Timeline` https://github.com/KissKissBankBank/kitten/pull/2057
- [RemoveRadium] Remove from `LegoGrid` https://github.com/KissKissBankBank/kitten/pull/2058
- [RemoveRadium] Remove from `Hero` https://github.com/KissKissBankBank/kitten/pull/2059
- [RemoveRadium] Remove from `RewardCard` https://github.com/KissKissBankBank/kitten/pull/2060
- [RemoveRadium] Remove from Lendo annexe `SimpleTemplate` https://github.com/KissKissBankBank/kitten/pull/2061
- [RemoveRadium] Remove from `PreDeposit` page https://github.com/KissKissBankBank/kitten/pull/2062

Il reste ces quelques sujets à traiter :

- `Carousel` (le vieux, dans `carousel/carousel`).
La principale différence avec le nouveau, c’est que le vieux est inclus dans une grid, et le nouveau ne l’est pas (à confirmer par @Morgan-jarry qui a fait le nouveau). De ce fait on pourrait tout à fait ajouter une prop au nouveau, et remplacer l’ancien automatiquement. Est-ce qu’il y a d’autres différences, ou des raisons pour lesquelles on ne peut pas le faire ?
- `KarlButtonIconFilter`, `KarlFooterKisskiss`, `KarlFooterLendo` et `ProjectsCarousel`
Ces objets sont spécifiques au styleguide Karl et n’ont pas de Story. `ProjectsCarousel`  a l’air d’être un doublon de la story qui existe,  pour `KarlButtonIconFilter`, `KarlFooterKisskiss`, `KarlFooterLendo`, est-ce qu’il est pertinent d’en faire des stories ? (si c’est présent sur Lendo ou KissKiss je dirais oui, sinon, non. Les Footers par exemple n’ont pas l’air d’être les mêmes que ceux en lignes actuellement, mais je me trompe peut-être)

Dites-moi ce que vous en pensez. Et n’hésitez pas à regarder le code pour me valider ces PR, pendant que je les teste sur mon KissKiss local
