### ISSUE TITLE
[Buttons] Refonte des boutons sociaux

### ISSUE THREAD

**Issue by LanF3usT** [KissKissBankBank/kitten#1900]
## Objectif

Les boutons `FacebookButtonIconWords`, `TwitterButtonIconWords` et `LinkedinButtonIconWords` sont encore sur l'ancien bouton. Il faudrait les passer sur la version récente du composant.

## Pourquoi

Suite à l'intégration de `FacebookButtonIconWords` dans une modale, celui-ci ne s'affiche pas de manière optimale en dessous d'une certaine taille.

<img width="220" alt="Capture d’écran 2019-12-26 à 11 27 44" src="https://user-images.githubusercontent.com/736319/71472306-c8945080-27d2-11ea-97f8-5cedb11c8bdb.png">

**Comment by joachimesque** [comment]
#2170
