### ISSUE TITLE
[HomePage] ProgressRing component 

### ISSUE THREAD

**Issue by camilledel** [KissKissBankBank/kitten#1957]
Maquette : 
https://app.abstract.com/projects/d3c9cfea-1f3f-4b0a-afda-4cd28684a358/branches/c4615852-88c0-44e6-b01b-49ef5ca36243/commits/06d246a497a3e793e1efdafbe5464c0e396e7d4e/files/49937cfa-e29f-46bf-a666-06ee1c4cdee2/layers/D1AD5938-830D-4674-96FE-C4A2102686DA

**Comment by joachimesque** [comment]
#1962
