### ISSUE TITLE
Multi-level select

### ISSUE THREAD

**Issue by solenema** [KissKissBankBank/kitten#268]
https://app.zeplin.io/project.html#pid=57a45b56f0c3427e3c985a7d&sid=57bb1f8c21f7ef844bb10d25

**Comment by sunny** [comment]
Testable sur la PR #325 !

**Comment by MathieuManchin** [comment]
<img width="562" alt="capture d ecran 2016-12-29 a 15 14 30" src="https://cloud.githubusercontent.com/assets/18660345/21545672/ae562eba-cdd9-11e6-85fd-30fb63da2730.png">


- [ ] taille M responsive, un décalage sur la dropdown en haut à droite

**Comment by sunny** [comment]
Pour ce bug on l'avait déjà spotté avec le Select précédent et il dépends de la largeur de l'écran. On dépends un peu de la librairie qui nous fait ce Select. :/

En général nos Select sont à une taille fixe, donc on peut toujours adapter sa largeur au moment de l'intégrer sur une plateforme, dans un formulaire dédié, pour éviter de tomber sur une mauvaise largeur.
