### ISSUE TITLE
Text input with unit - modifier width 

### ISSUE THREAD

**Issue by kevlag** [KissKissBankBank/kitten#292]
Modifier la largeur de la div contenant l'unité pour être synchro avec les boutons "Select"
Pour les text-input default : width :40px 
Pour les text-input small : width : 30px 

cf image
![textinput-unit](https://cloud.githubusercontent.com/assets/3010236/21310999/52a4ccc6-c5e5-11e6-8e4a-1525813bdd8b.jpg)

**Comment by camilledel** [comment]
Voir la PR #295
