### ISSUE TITLE
Composant Stepper

### ISSUE THREAD

**Issue by solenema** [KissKissBankBank/kitten#318]
https://app.zeplin.io/project.html#pid=57a45b56f0c3427e3c985a7d&sid=58594377aad74fb4070e57f5

**Comment by LanF3usT** [comment]
On peut lister ici tous les retours liés au `Stepper`. Lâchez-vous ou pas…

Liée à la PR https://github.com/KissKissBankBank/kitten/pull/320

Capture :

<img width="1278" alt="capture d ecran 2016-12-29 a 11 00 34" src="https://cloud.githubusercontent.com/assets/736319/21541389/0f4ff76a-cdb6-11e6-8d3a-995064c0dc20.png">

**Comment by Ynote** [comment]
@LanF3usT est trop fort. Pas de retour, je clos donc cette issue.
