### ISSUE TITLE
Syntaxe du unreleased du CHANGELOG

### ISSUE THREAD

**Issue by sunny** [KissKissBankBank/kitten#322]
En comparant le diff du CHANGELOG entre [le commit de merge](https://github.com/KissKissBankBank/kitten/commit/b2f1b0c10c74a6021d4a109586ebba932047aa16) et [la PR](https://github.com/KissKissBankBank/kitten/pull/314/files) on voit que dans la résolution du merge automatique il a décidé de placer le code sous `v4.2.0` au lieu de le garder sous `unreleased` car le code autour, lui n'avait pas changé. ([Diff](https://github.com/KissKissBankBank/kitten/commit/684fb55d4006f6d6fa6e3be3bd016b78fb86f9ae).)

Une solution serait de toujours merge changer la syntaxe et de faire le déplacement uniquement au moment de release. Exemple de syntaxe qui fonctionnerait :

Au lieu de:

```md
## [unreleased]

Features:
- Great new gooey thing

Fixes:
- Foo and bar
```

On pourrait avoir

A)

```md
Unreleased features:
- Great new gooey thing

Unreleased fixes:
- Foo and bar
```

B)

```md
- Unreleased fix: Foo and bar
- Unreleased feature: Great new gooey thing
```

C)

```md
## [unreleased]

- Fix: Foo and bar
- Feature: Great new gooey thing
```

Je crois que ma syntaxe préférée est la C.

**Comment by LanF3usT** [comment]
Ca me va aussi la syntaxe de la C même si la A fait moins de taff au moment de la release.

**Comment by sunny** [comment]
La C permets aussi de ne pas trop s'embêter avec l'ordre pendant qu'on fait des PRs. C'est au releaser de les réordonner.

**Comment by Ynote** [comment]
Je me permets de clore cette issue vu que le choix final s'est porté sur l'option C.
