### ISSUE TITLE
Fix: Shadow from select

### ISSUE THREAD

**Issue by kevlag** [KissKissBankBank/kitten#344]
<img width="121" alt="select" src="https://cloud.githubusercontent.com/assets/3010236/21764384/10b94d12-d663-11e6-92e6-7d1be792507e.png">

Enlever l'ombre portée

**Comment by Morgan-jarry** [comment]
We need to remove this line `assets/stylesheets/kitten/components/form/_select.scss:L497`

```
// box-shadow: 0 1px 0 rgba(0, 0, 0, .06);
```

To remove the shadow.

**Comment by Ynote** [comment]
Closed with https://github.com/KissKissBankBank/kitten/pull/478.
