### ISSUE TITLE
Styleguide files architecture

### ISSUE THREAD

**Issue by Ynote** [KissKissBankBank/kitten#353]
L'idée est de supprimer l'engine `kitten` : 
- [ ] remonter le dossier `spec/dummy` à la racine de `kitten` et le renommer `styleguide` ou `karl`.
- [ ] vérifier que les chemins et les configurations fonctionnent lorsque l'on lance le serveur.
- [ ] déplacer tous les fichiers de l'engine dans le styleguide (`/app`, `/config`, etc.).
- [ ] supprimer `lib` et le gemspec.
- [ ] mettre à jour la documentation dans le README et le wiki.

**Comment by bsartek** [comment]
Est-ce que cet issue est toujours d'actu @Ynote  ?
Si oui p'tête du coup on rajoute :
- [ ] adapter `bin/kitten`

**Comment by Ynote** [comment]
Non, cette issue n'est plus d'actualité. Il me semble qu'on l'avait ouverte pour extraire complètement le styleguide dans une application Rails.

**Comment by Ynote** [comment]
Mais remarque, on pourrait le da
