### ISSUE TITLE
Placeholder can go over "€" on inputs

### ISSUE THREAD

**Issue by sunny** [KissKissBankBank/kitten#361]
<img width="208" alt="screen shot 2017-01-11 at 17 27 18" src="https://cloud.githubusercontent.com/assets/132/21861389/f64aa894-d834-11e6-9999-94f5f413401d.png">

**Comment by Ynote** [comment]
@Morgan-jarry est-ce que cette issue ne serait-elle pas réglée avec https://github.com/KissKissBankBank/kitten/pull/455 (le `table-cell`) ?

**Comment by Morgan-jarry** [comment]
Oui cette PR corrige ce problème ;)
