### ISSUE TITLE
Liste des composants React pour la step 1.1

### ISSUE THREAD

**Issue by LanF3usT** [KissKissBankBank/kitten#362]
Composants restant à créer : 

- [x] HeaderTitles (@LanF3usT)
- [x] MakerWhoAmIStep
- [x] MakerForm

Composants terminés : 

- [x] Paragraph
- [x] Title
- [x] Button
- [x] Checkbox
- [x] RadioButton
- [x] DocLinkBox
- [x] FormActions
- [x] Grid
- [x] Stepper
- [x] SideGrid / SideGridContent / SideGridAside
- [x] HeaderGrid
- [x] HeaderLogo

**Comment by LanF3usT** [comment]
En discutant avec @Ynote, on s'est dit que ca pouvait être intéressant d'avoir un composant `Grid` pour gérer ce genre de bout de code : 

```html
<div class="k-Grid">
  <div class="k-Grid__col--12
              k-Grid__col--10@s
              k-Grid__col--8@l
              k-Grid__col--offset-1@s">
    …
  </div>
</div>
```

Ca donnerait un truc dans ce style : 

```html
<Grid>
  <GridCol col="12" col-s="10" col-l="8" offset-s="1">
    …
  </GridCol>
<Grid>

<!-- OR -->

<Grid>
  <GridCol cols="{ default: { col: 12 }, s: { col: 10, offset: 1 }, l: { col: 8 } }">
    …
  </GridCol>
<Grid>
```

J'ai l'impression qu'en soit le composant n'apporte pas grand chose à part être peut-être plus lisible que la version avec des classes. Vous en pensez quoi ? (@camilledel @sunny)

**Comment by sunny** [comment]
Je pense qu'il y a un certain nombre de composants React qui ne vont pas apporter grand chose mais qui simplifieront les mises à jour à l'avenir. Si à terme les applications ne sont liées qu'au JS, ça sera beaucoup plus facile de faire des mises à jour (et des dépréciations).

Je crois que je préfère la version courte de `GridCol` mais la version avec un objet est intéressante.
