### ISSUE TITLE
AddFormField component

### ISSUE THREAD

**Issue by kevlag** [KissKissBankBank/kitten#400]
Nouveau composant sur kitten. 

Création d'un champ de formulaire au clic sur le composant

https://zpl.io/ZO5om9

**Comment by solenema** [comment]
Composant à prototyper sur un formulaire pour voir comment il se comporte en interaction, en situation.

**Comment by LanF3usT** [comment]
Pour le formulaire `https://zpl.io/Z2oyiEp` du CIP, il va nous falloir ce composant.
