### ISSUE TITLE
DatePicker component

### ISSUE THREAD

**Issue by kevlag** [KissKissBankBank/kitten#401]
Utiliser la librairie open source d'AriBnb pour créer ce composant.
[inVision](https://projects.invisionapp.com/d/main#/console/15956988/331007401/preview)
https://github.com/airbnb/react-dates

**Comment by Morgan-jarry** [comment]
Le composant serait nécessaire pour la page [indicateurs de performance](https://www.lendopolis.com/indicateurs-de-performance) sur LENDO.
