### ISSUE TITLE
TextInputWithLimit

### ISSUE THREAD

**Issue by MathieuManchin** [KissKissBankBank/kitten#406]
Nouveau champ de formulaire avec limite de texte. 
https://zpl.io/ZVndX1

**Comment by MathieuManchin** [comment]
<img width="870" alt="capture d ecran 2017-02-16 a 16 55 48" src="https://cloud.githubusercontent.com/assets/18660345/23028847/d599c7ba-f468-11e6-8387-dc1e0c1abdb3.png">
Sur windows, une flèche apparait

**Comment by sunny** [comment]
Je croix que t'es pas une flèche.
