### ISSUE TITLE
Dans les tests, lever une exception à chaque warning

### ISSUE THREAD

**Issue by sunny** [KissKissBankBank/kitten#452]
Pour éviter d'avoir des warnings en production : https://gist.github.com/scmx/d98cc058a7c3dfef7890

**Comment by LanF3usT** [comment]
Que pensez-vous de changer l'affichage des tests avec des points ? Ca permet de voir les warnings qui apparaissent déjà mais tout en haut. Ce qui n'était pas évident à voir avec le recap textuel.

<img width="1279" alt="capture d ecran 2017-03-10 a 17 36 26" src="https://cloud.githubusercontent.com/assets/736319/23803878/4449ff4e-05b8-11e7-8142-9770eb46f69f.png">

(cc @Ynote, @sunny)

**Comment by Ynote** [comment]
J'aime bien l'idée pour lancer l'ensemble des tests. Mais lorsqu'on utilise la commande pour un seul fichier de test, j'aime bien avoir toutes les assertions.

**Comment by Ynote** [comment]
Aujourd'hui, c'est plutôt @camilledel et @Morgan-jarry qui intègrent des composants et qui écrivent des tests. Qu'est-ce qui vous semble le mieux pour éviter de manquer les warnings (en attendant que je l'implémente dans les tests) ?

**Comment by camilledel** [comment]
Pour l'instant laissons les warnings lorsqu'on lance les tests, étant donné que lorsqu'on lance les tests on lance que ceux du composant à tester. Du coup les warnings sont lisibles et accessibles.
