### ISSUE TITLE
Retour sur le template Mangopay

### ISSUE THREAD

**Issue by camilledel** [KissKissBankBank/kitten#472]
Ne pas faire attention aux icons Dashlane ils apparaîtront pas sur la version finale.

![capture d ecran 2017-02-22 a 16 01 01](https://cloud.githubusercontent.com/assets/11648042/23217046/45c2df0a-f918-11e6-82ff-1246b7d52156.png)

**Comment by MathieuManchin** [comment]
- [ ] la hauteur des input n'est pas bonne, elle doit être de 50px.
- [ ] mettre le annuler le paiement en dessous du valider (margin top/bottom de 20px)
- [ ] ajouter un BG sur le body #fbfbfb
- [ ] mettre les input en sources sans pro 
- [ ] mettre la couleur des placeholder en #B8B8B8

**Comment by MathieuManchin** [comment]
sur firefox
<img width="918" alt="capture d ecran 2017-02-22 a 16 22 05" src="https://cloud.githubusercontent.com/assets/18660345/23217943/1b774864-f91b-11e6-901d-8c80c10e0e03.png">

sur safari
<img width="550" alt="capture d ecran 2017-02-22 a 16 22 56" src="https://cloud.githubusercontent.com/assets/18660345/23217974/35561256-f91b-11e6-8dc1-4705cc3c650e.png">
