### ISSUE TITLE
Pb placeholder on Safari

### ISSUE THREAD

**Issue by camilledel** [KissKissBankBank/kitten#482]
<img width="1022" alt="capture d ecran 2017-02-24 a 17 43 10" src="https://cloud.githubusercontent.com/assets/11648042/23314964/5608c5d4-fac4-11e6-898a-0fe8a435524e.png">

**Comment by Morgan-jarry** [comment]
@camilledel : J'ai trouvé comment résoudre le problème, il faut supprimer le padding du placeholder (`.k-TextInput::placeholder`). 
Le padding doit être sur l'input, pas le placeholder.
