### ISSUE TITLE
Créer un composant pour gérer les messages d'erreur.

### ISSUE THREAD

**Issue by camilledel** [KissKissBankBank/kitten#483]
ex de composant ou on utilise un message d'erreur : 
- textInput
- locationInput
 
On pourrait créer un composant du styles `CheckboxesWithError` ? ou un composant générique `FormError`

**Comment by sunny** [comment]
Donc :
- renommer `k-TextInputWithInfo__error` en `k-FormInfo__error`
- ajouter des exemples de text input, checkboxes et radios dans le styleguide avec un texte d'erreur
