### ISSUE TITLE
Fix: child item height in a flex parent fails on Safari

### ISSUE THREAD

**Issue by LanF3usT** [KissKissBankBank/kitten#489]
Sur `Safari < 10`, le `height: 100%` ne semble pas fonctionner dans un parent avec un `flex-basis: 100%`.

Sources : 
- https://github.com/philipwalton/flexbugs#11-min-and-max-size-declarations-are-ignored-when-wrapping-flex-items
- https://bugs.webkit.org/show_bug.cgi?id=137730

**Comment by Ynote** [comment]
@LanF3usT Est-ce qu'on a contourné ce bug d'une autre manière ?

**Comment by LanF3usT** [comment]
De mémoire sur LENDO, j'ai carrément viré la fonctionnalité de flex-basis. Du coup, ce n'est toujours pas réglé.
