### ISSUE TITLE
Croix sur IE sur le text input with limit

### ISSUE THREAD

**Issue by sunny** [KissKissBankBank/kitten#491]
<img width="870" alt="d599c7ba-f468-11e6-8387-dc1e0c1abdb3" src="https://cloud.githubusercontent.com/assets/132/23465937/fefe0428-fe99-11e6-8341-a0af00243250.png">

(Reporté par Mathieu sur #406.)

**Comment by Ynote** [comment]
@camilledel est-ce qu'on a fixé ça ?

**Comment by joachimesque** [comment]
Voir solution proposée pour #1526
