### ISSUE TITLE
Prevent value to be deleted from `SelectWithState` component

### ISSUE THREAD

**Issue by Morgan-jarry** [KissKissBankBank/kitten#498]
Screenshot:
![image](https://cloud.githubusercontent.com/assets/523306/23550022/3a85e22e-000f-11e7-915e-cd17b4693664.png)

When a user press `delete` touch on a focused select, the value is deleted.
C.F.: https://github.com/JedWatson/react-select (`deleteRemoves`).

**Comment by Ynote** [comment]
Et du coup, c'est un comportement qu'on ne veut pas ? Je ne sais pas quelles sont les bonnes pratiques concernant les selects au clavier. @LanF3usT @camilledel ?

**Comment by LanF3usT** [comment]
C'est un comportement étrange qui est dû au faite que `react-select` est un mélange de Select et d'AutoCompletion avec la possibilité de faire une recherche.

Dans notre cas, je suis d'avis de rendre un select simple sans cette option et d'avoir un comportement identique au select de base.
