### ISSUE TITLE
Fix focus color when k-TextInputWithUnit__unit is in error

### ISSUE THREAD

**Issue by sunny** [KissKissBankBank/kitten#507]
<img width="227" alt="screen shot 2017-03-08 at 16 20 51" src="https://cloud.githubusercontent.com/assets/132/23709911/42424cc2-041b-11e7-9bf8-f73d4b072e65.png">

**Comment by Morgan-jarry** [comment]
Enfaite le bug n'est pas lié au composant, il fonctionne parfaitement sur kitten.
Je pense que le problème viens du css de KissKissBankBank, il faut surcharger la couleur au focus.

**Comment by sunny** [comment]
Ah mince, je recrée l'issue sur KissKiss du coup 👍
