### ISSUE TITLE
Feature: `SummaryTable` component

### ISSUE THREAD

**Issue by LanF3usT** [KissKissBankBank/kitten#508]
Création d'un composant Table : `StatementTable` ?

Screenshot :

<img width="665" alt="capture d ecran 2017-03-08 a 16 19 28" src="https://cloud.githubusercontent.com/assets/736319/23711722/f60f32c4-0420-11e7-9619-83609ac353b3.png">

Lien Zeplin : http://zpl.io/icLGi

Exemples d'utilisation : http://zpl.io/Z1lJJFm (dans le formulaire ainsi que dans la colonne de droite)

**Comment by sunny** [comment]
Il faut sans doute trouver un nom plus générique que "StatementTable" (et moins générique que "Table").

**Comment by Ynote** [comment]
Je suis d'accord pour trouver quelque chose de moins générique que `Table`.

Si on trouve autre chose que `Statement`, je suis d'avis de prendre ça. Mais si on ne trouve pas, on avait dit jusque là qu'on nommait les composants avec les cas précis qu'on connaissait (comme pour `PlatformSwitch`) et du coup, le fait que ce soit effectivement très explicite ne me gêne pas.

**Comment by sunny** [comment]
`EntriesTable` ? `ValuesTable` ? Sous-entendu tableau à deux entrées seulement ?

**Comment by Ynote** [comment]
`DoubleEntriesTable` ?

**Comment by sunny** [comment]
`DefinitionList` ?
`Values` ?

**Comment by Ynote** [comment]
J'aime bien `DefinitionList`.

**Comment by sunny** [comment]
Ce que j'aime pas avec définition c'est que 500 € c'est pas vraiment la définition de Montant de votre prêt.

`Answers`, `DataList`, `Infos` ? #the-name-game ?

**Comment by Ynote** [comment]
Est-ce que du coup, on resterait pas plus focus sur ce que fait ce composant actuellement plutôt que de trouver un nom plus générique pour ce layout (alors qu'on n'a pas encore de cas similaire) ?

**Comment by LanF3usT** [comment]
`InformationTable` ?

**Comment by LanF3usT** [comment]
Exemple de structure HTML : 

```html
<table class="k-InformationTable">
  <tr class="k-InformationTable__row">
    <th class="k-InformationTable__title" scope="row">
      Montant de votre prêt
    </th>
    <td class="k-InformationTable__info">
      500&nbps;*
    </td>
  </tr>
</table>
```

**Comment by camilledel** [comment]
Ok donc on reste sur `InformationTable` ?

**Comment by sunny** [comment]
`AmountList` ?

**Comment by sunny** [comment]
(Parce que @Ynote aime pas trop `InformationTable` qu'est trop générique et que c'est pas trop une table et que des information ça veut tout et rien dire.)

**Comment by Ynote** [comment]
Oui oui je confirme que j'ai bien dit ça.

**Comment by LanF3usT** [comment]
Comme il vous siéra. Je vous fais confiance ! :)

**Comment by LanF3usT** [comment]
Le composant a été développé sous le magnifique nom de `InfoLines`. De ce fait, je clôture cette PR.
