### ISSUE TITLE
Feature: Add MasterCard icon

### ISSUE THREAD

**Issue by LanF3usT** [KissKissBankBank/kitten#516]
Pour la page paiement de LENDO, il faudrait créer l'icône MasterCard : 

<img width="118" alt="capture d ecran 2017-03-13 a 15 11 17" src="https://cloud.githubusercontent.com/assets/736319/23858105/ae12db3c-07ff-11e7-810e-9cc6ddcfca6c.png">

**Comment by Ynote** [comment]
Est-ce qu'on a le svg pour cette icône ?

**Comment by Morgan-jarry** [comment]
@kevlag @MathieuManchin ⬆️

**Comment by LanF3usT** [comment]
À voir avec le produit…
