### ISSUE TITLE
Feature: Add CB icon

### ISSUE THREAD

**Issue by LanF3usT** [KissKissBankBank/kitten#517]
Pour la page paiement de LENDO, il faudrait créer l'icône CB :

<img width="121" alt="capture d ecran 2017-03-13 a 15 12 50" src="https://cloud.githubusercontent.com/assets/736319/23858293/387146b0-0800-11e7-8e55-2201a6fa73c5.png">

**Comment by Ynote** [comment]
Idem que pour MasterCard, est-ce qu'on a le svg quelque part ?

**Comment by sunny** [comment]
Peut sans doute être fait en même temps que #516

**Comment by LanF3usT** [comment]
À voir avec le produit…
