### ISSUE TITLE
Feature: `LegoGrid` component

### ISSUE THREAD

**Issue by LanF3usT** [KissKissBankBank/kitten#528]
Création d'une grille qui aligne correctement n items sous forme de "brique".
Cette grille sera utilisée sur la page `browsing` des plateformes.

Exemple de composant React : https://github.com/eiriklv/react-masonry-component
Zeplin : http://zpl.io/lLPwC

À vos briques !

![more-lego-bricks](https://cloud.githubusercontent.com/assets/736319/23954346/50d50e7e-0997-11e7-923f-6eb8daef62e4.jpg)

**Comment by sunny** [comment]
Il y a un gros problème avec ce layout en fait : c'est qu'on ne peut pas les trier dans le DOM de gauche à droite, on doit les trier de haut en bas. Vous voyez une solution ?

**Comment by LanF3usT** [comment]
Oui le lien était surtout pour montrer de quoi on parle. C'était pas forcement la solution. On va devoir se tourner vers des composants JS du type : https://github.com/eiriklv/react-masonry-component

**Comment by sunny** [comment]
👍
