### ISSUE TITLE
Fix: Changer la couleur des éléments de formulaire pour les états d'erreur

### ISSUE THREAD

**Issue by Ynote** [KissKissBankBank/kitten#530]

**Comment by Morgan-jarry** [comment]
Je ne suis pas sûr de bien comprendre, ce n'est pas déjà le cas ?
![image](https://cloud.githubusercontent.com/assets/523306/24000336/3e0acec2-0a5b-11e7-997e-d6552e131eab.png)

**Comment by sunny** [comment]
Les maquettes sur Zeplin ont changé. La couleur du texte dans l'input doit rester noire et pas être en rouge.
