### ISSUE TITLE
Un changement de styles peut-il être défini comme un `breaking change` ?

### ISSUE THREAD

**Issue by LanF3usT** [KissKissBankBank/kitten#546]
**Débat :** 

On a eu un débat intéressant avec @sunny hier soir sur le sujet des `breaking change` provoqués par les styles CSS. Ca peut être intéressant de recueillir vos avis sur le sujet afin d'identifier plus facilement quand on fait des `breaking change`.

**Comment by LanF3usT** [comment]
Pour ma part, un changement de styles peut provoquer un `breaking change` à partir du moment où il modifie la structure de la page (margin, padding, with, height, etc.).
Si l'UX du site change, c'est un `breaking change` car ca impose à la plateforme de faire le nécessaire pour conserver l'UX/structure ou bien l'accepter.

À l'inverse si on modifie la couleur d'un texte, si on ajoute un border-radius, même si on ajoute une bordure d'1px mais on ajoute le `box-sizing: border-box`, ce n'est pas un `breaking change`.

**Comment by Ynote** [comment]
J'aime bien l'idée de considérer que les modifications qui impliquent un changement de layout sont des `breaking changes`. 

On pourrait peut-être lister les déclarations qui sont affectées : 
- les marges et les paddings
- les dimensions
- le display 
- la taille de typographie ?

**Comment by Morgan-jarry** [comment]
Mais, si les marges et/ou padding sont modifiés mais que la dimension du composant reste la même, ce n'est pas un `breaking change`, si ?

**Comment by LanF3usT** [comment]
Ca va vraiment dépendre du composant. On aura à se poser la question à chaque fois.

Exemple avec cette PR (https://github.com/KissKissBankBank/kitten/pull/514), pour moi, on est dans un cas de `Breaking change` car sur LENDO, je vais devoir clean les marges que j'ai pu mettre sur les éléments composant le `content`.

**Comment by LanF3usT** [comment]
Autre cas de `breaking change` dû aux styles : 

Sur LENDO, nous avons perdu le `width: 100%` sur `.k-TextInputWithUnit` car il faut maintenant ajouter la classe `.k-TextInputWithUnit--fullWidth` pour que ca fonctionne.

<img width="336" alt="capture d ecran 2017-03-27 a 19 05 38" src="https://cloud.githubusercontent.com/assets/736319/24368502/f4da591a-1320-11e7-8301-96aa63ba2815.png">

**Comment by Ynote** [comment]
Je propose d'acter déjà pour les principales déclarations CSS qui me semblent être forcément des `breaking changes` et y faire attention pendant les reviews : 
- les marges et les paddings
- les dimensions
- le display

Effectivement, jusque là, on a évité ce genre d'erreur parce qu'on avait une bonne connaissance de la librairie. Elle grandit trop vite pour qu'on ne place pas ces changements dans le `CHANGELOG`.
