### ISSUE TITLE
[MangoPay payment page] - Fix: update SVG image

### ISSUE THREAD

**Issue by kevlag** [KissKissBankBank/kitten#557]
Nous avons reçu l'image "Powered by Mangopay" en SVG. Ça serait bien de la remplacer par celle actuelle

**Comment by Ynote** [comment]
@solenema @kevlag Que fait-on de cette issue ? Elle ne devrait pas vraiment être dans Kitten (mais je sais qu'on n'a pas non plus d'endroit où la mettre).

**Comment by sunny** [comment]
Du coup on a dit qu'on la garde ouverte jusqu'à ce que @camilledel puisse appliquer ces changements.
