### ISSUE TITLE
[MangoPay payment page] - Fix: margin-top

### ISSUE THREAD

**Issue by kevlag** [KissKissBankBank/kitten#558]
Le formulaire est trop collé au haut de l'écran, mettre un margin-top de 50px au moins.

**Comment by Ynote** [comment]
@solenema @kevlag Que fait-on de cette issue ? Elle ne devrait pas vraiment être dans Kitten (mais je sais qu'on n'a pas non plus d'endroit où la mettre).

**Comment by sunny** [comment]
Du coup on a dit qu'on la garde ouverte jusqu'à ce que @camilledel puisse appliquer ces changements.
