### ISSUE TITLE
[MangoPay payment page] - Fix: border-radius

### ISSUE THREAD

**Issue by kevlag** [KissKissBankBank/kitten#559]
Mettre un border-radius de 16px sur le formulaire

**Comment by Ynote** [comment]
@solenema @kevlag Que fait-on de cette issue ? Elle ne devrait pas vraiment être dans Kitten (mais je sais qu'on n'a pas non plus d'endroit où la mettre).

**Comment by solenema** [comment]
oui, attendons juste que @camilledel fasse les modifs sur le template, et nous les fermerons.
