### ISSUE TITLE
Bug with react_component and stateless component

### ISSUE THREAD

**Issue by Morgan-jarry** [KissKissBankBank/kitten#561]
Example of error :
```
Exception in rendering!

Message: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in.

Error: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in.
    at invariant (eval at <anonymous> (<eval>:414:2), <anonymous>:44:15)
    at instantiateReactComponent (eval at <anonymous> (<eval>:1064:2), <anonymous>:79:23)
    at eval (eval at <anonymous> (<eval>:1446:2), <anonymous>:44:31)
    at ReactServerRenderingTransaction.perform (eval at <anonymous> (<eval>:634:2), <anonymous>:140:20)
    at renderToStringImpl (eval at <anonymous> (<eval>:1446:2), <anonymous>:43:24)
    at Object.renderToString (eval at <anonymous> (<eval>:1446:2), <anonymous>:73:10)
    at serverRenderReactComponent (eval at <anonymous> (<eval>:1740:2), <anonymous>:86:37)
    at Object.serverRenderReactComponent (eval at <anonymous> (<eval>:120:2), <anonymous>:235:53)
    at <eval>:5:23
    at <eval>:12:3
```

The code which render this error is the following :

```js
import React from 'react'
import classNames from 'classnames'

export const SupTitle = props => {
  const { className, tag, ...supTitleProps } = props

  const supTitleClassName = classNames(
    'k-SupTitle',
    className,
  )

  const Tag = tag // is undefined if not set in `react_components`

  return (
    <Tag className={ supTitleClassName } { ...supTitleProps } />
  )
}

SupTitle.defaultProps = {
  tag: 'div',
  children: 'Sup Title',
}
```

The `defaultProps` doesn't seems to be take in account as `tag` props return `undefined` instead of `div` by default. This is why we get the error above.

**Comment by sunny** [comment]
Il faudrait mettre `tag: <div />` dans les `defaultProps` du coup ?

**Comment by LanF3usT** [comment]
En mode `stateless` et quand c'est appelé directement via `react_component`, les `defaultProps` ne sont pas pris en compte. Le bug a été constaté sur d'autres composants également. Les tests fonctionnent néanmoins et quand c'est appelé dans un autre composant, cela fonctionne également.

Je penche sur un bug de `react-on-rails` qui doit écraser tous les props par son propre objet `props` et du coup ne prend pas en compte les valeurs par défaut.

**Comment by sunny** [comment]
Ah ok.

Du coup on pourrait faire un exemple (genre `KarlSupTitle`) si on veut l'afficher sans erreur ?

Ou, sinon, représenter les groupes d'exemples en React, pour éviter d'avoir autant de `react_component`. Exemple:

```js
export const KarlTitles = () => (
  <KarlExampleGroup>
    <KarlTitle>Titles</KarlTitle>

    <KarlExample name="Superior title">
      <SupTitle>Title</SupTitle>
    </KarlExample>

    <KarlExample name="Title">
      <Title>Title</Title>
    </KarlExample>
  </KarlExampleGroup>
)
```

```haml
# app/views/groups/titles.haml
= react_component 'KarlTitles'
```

**Comment by LanF3usT** [comment]
Yep c'est une solution pour éviter le bug.

**Comment by Ynote** [comment]
@Morgan-jarry @LanF3usT @sunny Peut-on considérer que ce "bug" est réglé ? Et voir plus tard, si on peut faire une PR sur le repo de React on Rails pour gérer correctement les stateless components ?

**Comment by LanF3usT** [comment]
Maintenant qu'on le sait, quand on a besoin des `defaultProps`, on créé une classe à la place de la version `stateless`. Donc on peut dire que cette issue est assimilée mais le bug reste présent.

**Comment by Ynote** [comment]
Mais ca ne concerne pas vraiment Kitten. Plutôt React on Rails non ?

**Comment by LanF3usT** [comment]
Yep. Ma réponse n'était pas forcément claire. Je pense qu'on peut fermer cette issue car on sait maintenant comment faire pour contourner le problème de React on Rails. Ce bug n'est donc pas de notre côté.

**Comment by Ynote** [comment]
Ok merci pour ces explications !
