### ISSUE TITLE
Marges verticales

### ISSUE THREAD

**Issue by sunny** [KissKissBankBank/kitten#565]
Suite à l'intégration de la Card avec @LanF3usT, on s'est posé plein de questions sur les marges.

![](http://addonscms.com/107-thickbox_default/module-marge.jpg)

On en est venu à différentes conclusions :
- Les grilles sont là pour gérer les marges horizontales, les composants eux-mêmes doivent gérer les marges verticales
- Les marges entre les éléments dépendent généralement d'un conteneur (Card, LoanSimulator, …)
- Les marges dans les maquettes sont des multiples de 10px alors que nos marges par défaut  sur les textes (titres, sous-titres, paragraphes) dépendent de la typo (16px, 19px, …)
- On a souvent besoin d'appeler nos helpers CSS pour appliquer des marges

On en est venu à l'idée qu'on puisse créer un attribut `vmargin` qui permettrait d'exprimer quel multiplicateur de marge utiliser (simple, double, triple, etc.) sur les composants.

Ça pourrait donner le pseudo-code suivant :

```jsx
<SupTitle vmargin="2 1">
  Étape 1
</SupTitle>
<Paragraph vmargin={`1 ${this.props.large ? 2 : 0}`}>
  Ceci est l'étape 1
</Paragraph>
<Div vmargin="1 0">
  <img src="…" />
</Div>
```

Pour ajouter cet attribut `vmargin` à nos composants, on s'aiderait d'une fonction. Par exemple :

```jsx
const Div = ({ vmargin, className, props... }) =>
  <div className={ classNames(className, vMargerClassName(vmargin)) } { ...props } />

const Paragraph = ({ vmargin, className, props... }) => {
  className = classNames("k-Paragraph", vMargerClassName(vmargin), className)
  return <p className={ className } { ...props } />
}
```

Qu'est-ce que vous en pensez ?

**Comment by sunny** [comment]
On pourrait même faire un high-order-component :

```jsx
export function withVMargins(WrappedComponent) {
  return ({ className, ...props }) => {
    className = classNames(className, "…")
    return <WrappedComponent className={ className } { ...props } />
  }
}
```

```jsx
const DefaultDiv = props => <div { ...props } />
const DefaultParagraph = ({ className, ...others }) => (
  <p className={ classNames("k-Paragraph", className) } { ...others } />
)

export const Div = withVMargins(DefaultDiv)
export const Paragraph = withVMargins(DefaultParagraph)
```

Ça pourrait même marcher sous forme de décorateur :

```jsx
@withVMargins
export const Div = props => <div { ...props } />

@withVMargins
export const Paragraph = ({ className, ...props }) => (
  <p className={ classNames("k-Paragraph", className) } { ...props } />
)
```

**Comment by Morgan-jarry** [comment]
Du coup on devrait rajouter cette props dans tout nos composants ? Ça ne risque pas d'être un peu laborieux ? :).

**Comment by camilledel** [comment]
On peut pas s'en passer au risque d'avoir un styleguide laborieux !

**Comment by camilledel** [comment]
Oui je dis pas le contraire non plus !! Mais c'est un travail de dur labeur !

**Comment by sunny** [comment]
@Morgan-jarry c'est pas faux. Utiliser un décorateur ça peut aider à éviter que ça soit trop laborieux.

On est peut-être pas obligé de le faire sur tous les composants.

Une autre solution serait d'utiliser un composant qui gère les marges. Genre `<VMargin />` qui wrappe une `<div />` à chaque fois, mais je n'ai pas l'impression que c'est idéal non plus en terme de code généré.

**Comment by LanF3usT** [comment]
Ca me parait bien avec le décorateur. On va commencer par le faire pour des composants qui gère déjà des marges verticales (`Paragraph`, `Title`, etc.) ainsi que la création du composant `Div`?

Je pense qu'avec déjà ca, on couvre pas mal de cas qu'on aurait dû gérer à chaque fois avec des `k-u-margin-…-…`.

**Comment by LanF3usT** [comment]
Pour `ProjectCard`, ca pourrait donner un truc comme : 

```js
export const ProjectCard = props => {
  return (
    <div className="k-ProjectCard">
      <div className="k-ProjectCard__grid">
        <Div vmargin="1 1" className="k-ProjectCard__flex">
          <ButtonImage />
          <Paragraph vmargin="0 0" />
          <IconBadge />
        </Div>

        <Title vmargin="1 1">Titre du projet</Title>
        <Div vmargin="1 1">
          <TagList />
        </Div>
        <Paragraph vmargin="1 1">Description du projet</Paragraph>

        <Div vmargin="1 1" className="k-ProjectCard__flex">
          <Paragraph vmargin="0 0" />
          <IconBadge />
          <Paragraph vmargin="0 0" />
        </Div>
      </div>

      <div className="k-ProjectCard__grid">
        <Div vmargin="1 1" className="k-ProjectCard__flex">
          <Progress className="k-ProjectCard__flex__fluid" />
          <span>42 %</span>
        </Div>
      </div>
    </div>
  )
}
```

**Comment by Morgan-jarry** [comment]
Pour les typos, il faut également faire attention au `line-height`, qui influence l'espacement en plus de la marge :).

**Comment by LanF3usT** [comment]
Nouvelle proposition : 

```js
export const ProjectCard = props => {
  return (
    <div className="k-ProjectCard">
      <div className="k-ProjectCard__grid">
        
        <Marger top=".5" bottom="1.5" className="k-ProjectCard__flex">
          <ButtonImage />
          <Paragraph margin={ false } />
          <IconBadge />
        </Marger>

        
        <Marger top="1" bottom="1">
          <Title margin={ false }>Titre du projet</Title>
          <TagList />
          <Paragraph margin={ false }>Description du projet</Paragraph>
        </Marger>
        

        <Marger top="1" bottom="1" className="k-ProjectCard__flex">
          <Paragraph margin={ false } />
          <IconBadge />
          <Paragraph margin={ false } />
        </Marger>
        
      </div>

      <div className="k-ProjectCard__grid">

        <Marger top="1" bottom="1" className="k-ProjectCard__flex">
          <Progress className="k-ProjectCard__flex__fluid" />
          <span>42 %</span>
        </Marger>
        
      </div>
    </div>
  )
}
```

**Comment by Ynote** [comment]
Très bonne proposition ! 🐙 

Je note ici qu'il faut écrire un wiki sur la logique (reprendre la description de @sunny et @LanF3usT) de gestion les grids et les marges verticales.

L'expérience nous montre qu'on a rapidement dévié de notre principe premier, à savoir qu'un composant ne doit pas gérer lui-même son placement et c'est important de le noter quelque part.

**Comment by sunny** [comment]
Du coup comme nom de ce composant qui gère les marges verticales, on préfère quoi ?

- `<Marger top="1" />`
- `<Margin top="1" />`
- `<Marge top="1" />` : pas hyper anglais, mais est dans le dico comme synonyme archaïque de marge

![Marge Simpson](https://upload.wikimedia.org/wikipedia/en/0/0b/Marge_Simpson.png)

**Comment by Ynote** [comment]
Je vote pour `Marger`.

**Comment by LanF3usT** [comment]
Ca donnerait un truc dans le styles : 

```js
import React from 'react'

export const Marger = ({ top, bottom, props...) => {
  const gutter = 10
  const styles = {
    marginTop: top * gutter,
    marginBottom: bottom * gutter,
  }

  return (
    <div style={ styles } { ...props } />
  )
}

Marger.defaultProps = {
  top: 0,
  bottom: 0,
}
```

**Comment by LanF3usT** [comment]
Ouais `Marger` ca me parait bien. Je vote pour également.

**Comment by Morgan-jarry** [comment]
Et ça fait une fusion Marge <-> Homer !

**Comment by LanF3usT** [comment]
Ca irait dans le groupe `layout` ? autre ?

**Comment by Morgan-jarry** [comment]
Je dirai `layout` vu que c'est de la mise en page :).
