### ISSUE TITLE
Configuration unique pour les composants CSS et JS

### ISSUE THREAD

**Issue by LanF3usT** [KissKissBankBank/kitten#573]
Nous commençons à avoir des composants React qui dépendent de données que seul le CSS connait. Exemple : `Marger` qui aimerait récupérer la valeur de la gouttière ainsi que la taille globale de la font. On peut en imaginer d'autres qui aimeraient utiliser les couleurs directement dans le composant React sans devoir jouer avec n classes.

L'idée serait d'avoir une config JSON unique qui soit utilisable pour le CSS et le JS.

Il existe des librairies qui permettent de convertir du JSON en variables SASS : https://github.com/Updater/node-sass-json-importer

Qu'est-ce que vous en pensez ?

**Comment by camilledel** [comment]
Cool !

**Comment by Ynote** [comment]
J'aime bien l'idée de partager ces variables quelque part. Je suis très favorable à cette proposition 🐙

**Comment by Morgan-jarry** [comment]
Je valide 👍

**Comment by sunny** [comment]
Carrément.

**Comment by Ynote** [comment]
Sinon aussi du CSS modules : https://blog.bluematador.com/posts/how-to-share-variables-between-js-and-sass/

**Comment by LanF3usT** [comment]
Cool ton lien. Vivement qu'on est du temps pour toutes ses issues qui vont nous simplifier la vie !

**Comment by Ynote** [comment]
On peut fermer cette issue. Pour l'instant, on a deux fichiers de configuration similaires en js et en css.
