### ISSUE TITLE
Lock npm dependencies versions and check updates 

### ISSUE THREAD

**Issue by Ynote** [KissKissBankBank/kitten#601]
Je me suis rendue compte que le versioning des dépendances ne suivait pas toujours le [versioning semantique](http://semver.org/). 

Peut-être serait-il mieux de figer les versions des dépendances dans le `package.json` et d'avoir un script (ou d'ajouter au script de `bin/install`) qui output les mises à jour à effectuer sur les dépendances du module npm de `kitten`.

**Comment by sunny** [comment]
Est-ce que de passer à Yarn ne va pas nous aider à régler ce souci en ayant un fichier de lock de versions ?

**Comment by Ynote** [comment]
Oui, tu as tout à fait raison. Je suis ultra motivée pour passer à yarn.

Quand on aura des versions lockées sur les dépendances, une question me vient à l'esprit : est-ce important d'avoir des dépendances à jour ? Si oui, comment le gérer ?
