### ISSUE TITLE
Passer le tag en `p` à la place d'un `h1` dans `ProjectCard`

### ISSUE THREAD

**Issue by LanF3usT** [KissKissBankBank/kitten#630]
A la place d'avoir un `h1` au niveau du titre dans la `ProjectCard`, il faudrait avoir un `p`. Ca évite de casser la structure des titres d'une page ou alors il faut ajouter un peu de sémantique avec une balise de type `header` ou `section`.

https://github.com/KissKissBankBank/kitten/blob/master/assets/javascripts/kitten/components/cards/project-card.js#L44

**Comment by Morgan-jarry** [comment]
Il me semble que tu peux lui passer un tag dans les props.
