### ISSUE TITLE
Nouveau process de release

### ISSUE THREAD

**Issue by Ynote** [KissKissBankBank/kitten#710]
Lorsque la PR https://github.com/KissKissBankBank/kitten/pull/708 sera mergée, le déploiement continu sera en place pour le styleguide. 

Il faudrait avant : 
- [ ] <del>ajouter une branche `develop` qui servira à merger les features,</del>
- [ ] <del>changer la branche par défaut sur le repo git,</del>
- [ ] <del>mettre à jour le script de release pour pusher la branch `develop` à la place de `master`,</del>
- [ ] <del>mettre à jour le README pour switcher sur `develop` au lieu de master lors de la release.</del>

**Comment by Morgan-jarry** [comment]
Tu veux dire 
> mettre à jour le README pour switcher sur *`develop`* au lieu de master lors de la release
? :)

**Comment by sunny** [comment]
Avant qu'on ne fasse ça j'aimerais bien rediscuter de la branche `develop`. Je ne vois pas l'intérêt, pour moi ce n'est pas du déploiement continu et c'est une source de manipulations inutiles qui ajoute de la complexité au développement et au déploiement.

**Comment by Ynote** [comment]
Discutons-en cet apres-midi. On attendait ton retour justement parce qu'on connait ton avis a ce sujet.

**Comment by sunny** [comment]
- [ ] Ajouter une branche `styleguide`qui servira à merger les features
- [ ] Mettre à jour le script de release pour qu'après une release `git checkout styleguide ; git merge --ff-only styleguide ; git push origin styleguide ; git checkout master`
