### ISSUE TITLE
Tests du composant `ImageCropper`

### ISSUE THREAD

**Issue by LanF3usT** [KissKissBankBank/kitten#725]
Suite à cette PR https://github.com/KissKissBankBank/kitten/pull/642, il faudrait écrire les tests du composant `ImageCropper` et sans doute approfondir les tests des 2 autres composants.

Bon courage !

**Comment by sunny** [comment]
Escroc !

**Comment by Ynote** [comment]
Mauvaise personne !

**Comment by Ynote** [comment]
Débuté dans https://github.com/KissKissBankBank/kitten/pull/742.

**Comment by sunny** [comment]
Est-ce qu'on ferme cette issue ? On retravaillera sur les tests quand on retravaillera sur l'imagecropper, non ?
