### ISSUE TITLE
Réparer le `SearchInput` retirer `appearance: none` 

### ISSUE THREAD

**Issue by camilledel** [KissKissBankBank/kitten#730]

**Comment by Ynote** [comment]
@camilledel on peut fermer ?

**Comment by camilledel** [comment]
@Ynote : J'ai jamais réparé le composant sur le styleguide. Il est réparé uniquement sur kisskiss.
On l'a laisse ouverte pour l'instant

**Comment by camilledel** [comment]
Idem #817
