### ISSUE TITLE
Afficher les `icon` dans le styleguide

### ISSUE THREAD

**Issue by camilledel** [KissKissBankBank/kitten#752]
Pour présenter les icons sur le styleguide, est ce que vous pensez que ça sera plus lisible en les présentant dans un contexte neutre (en grand, icon en noir) ou directement dans un contexte c-à-d dans une `button` ? 
Ou on peut aussi présenter les icons de façon neutre et en mise en situation. 

Exemple de style guide présentant des icons de façon neutre : 
https://material.io/icons/
https://ux.mailchimp.com/patterns/icons

Autres points techniques :
- Actuellement nous avons certains icons en `.svg` (un tri doit être fait) qui sont dans `assets/images/icons` et tous les composants utilisés en react sont dans `components/icons/`.
Est ce que pour créer la page Icons, il vaut mieux que je regroupe tous les icons en `.svg` ou il vaut que j'utilise tous ceux en `.js` ?

cc @Ynote

**Comment by Ynote** [comment]
Pour la question de tech : je pense que les svg qui sont dans `assets/images/icons` sont du legacy (de lorsqu'on a lancé Kitten). Je serai d'avis de nettoyer tout ça au passage.\

Pour la présentation, je trouve que c'est mieux de les présenter de façon neutre parce qu'ils pourraient être utilisés dans des contextes différents et les afficher dans un `button`, ça biaise très légèrement la lecture. Ce n'est qu'un avis personnel. Il faut probablement demander aussi l'avis de l'équipe produit ?
