### ISSUE TITLE
[Styleguide] Avoir une belle page 404 pour le styleguide Kitten

### ISSUE THREAD

**Issue by LanF3usT** [KissKissBankBank/kitten#761]
https://styleguide.kisskissbankbank.com/404

**Comment by Ynote** [comment]
En fait, avoir une vraie page tout court déjà :D

**Comment by LanF3usT** [comment]
Oui mais si elle est belle, c'est encore mieux ;D

**Comment by Ynote** [comment]
Pour qu'elle soit belle, il faut en parler au produit. Probablement que ce ne sera pas prioritaire, mais ça lancera la discussion.

**Comment by sunny** [comment]
@cyrill62 @bsartek On fait comment pour setup une 404 sur le styleguide ?
