### ISSUE TITLE
Faire le ménage dans le fichier des imports de composant

### ISSUE THREAD

**Issue by LanF3usT** [KissKissBankBank/kitten#782]
Dans le fichier suivant https://github.com/KissKissBankBank/kitten/blob/master/spec/dummy/client/entries/app-kitten.js, l'ordre n'est plus respecté.

Il faudrait refaire une passe dessus pour avoir l'order alphabétique sur les groupes puis sur le nom du composant. Dans chaque groupe, on retrouve les composants ainsi que les exemples `Karl`.

Ca donnerait un truc du style : 
 
```js
// Group A.
import { ComponentA } from '…/components/{group-a}/component-a'
import { ComponentB } from '…/components/{group-a}/component-b'
import { KarlComponentA } from '…/karl/components/{group-a}/component-a'

// Group B.
import { ComponentA2 } from '…/components/{group-b}/component-a-2'
import { ComponentB2 } from '…/components/{group-b}/component-b-2'
import { KarlComponentA2 } from '…/karl/components/{group-b}/component-a-2'

ReactOnRails.register({
  // Group A.
  ComponentA,
  ComponentB,
  KarlComponentA,

  // Group B.
  ComponentA2,
  ComponentB2,
  KarlComponentA2,
})
```

**Comment by Ynote** [comment]
Pour les imports multiples dont les noms ne commencent pas par la même lettre genre : 
```js
import {                                                                       
  FacebookButtonIcon, 
  TwitterButtonIcon,
  LinkedinButtonIcon,
} from 'kitten/components/buttons/social-button-icon'
```
Je vais considérer que la lettre à prendre en compte, c'est celle du nom du fichier. Ça vous semble bien ?
