### ISSUE TITLE
Différencier les composants de rendu des composants de gestion d'état

### ISSUE THREAD

**Issue by LanF3usT** [KissKissBankBank/kitten#788]
Historique de la discussion : 

> Camille :
> Peut-être qu'il faut préciser la différence en ProjectSimilarCard et SimilarProjectsCard. Ils sont liés mais sans lire le code on sait pas ce qui les distingue.

> Fanny :
> C'est un point très juste à soulever. Est-ce qu'on a décidé d'une nomenclature/rangement de fichiers/autre idée révolutionnaire pour différencier des composants totalement statiques et des composants qui ne gèrent qu'un état ?
Ou est-ce que de simples commentaires sur chaque composant peut suffire ?
Vos avis ?

**Comment by LanF3usT** [comment]
J'ai l'impression que de simples commentaires peuvent faire l'affaire.

Sinon on pourrait avoir un préfixe de type `…View`, `…Template` pour les composants de simple rendu (Ex: `ProjectCard` > `ProjectCardView`).

Est-ce que la logique de dissociation des 2, on ne devrait pas l'avoir tout le temps même pour des petits composants ? Trop lourd pour des petits ?

**Comment by camilledel** [comment]
En vrai on différencie la view du comportement animé pour des composants qui peuvent vivre sans un comportement animé. Je suis pas sûr que ce soit une bonne idée de les distinguer pour tous les composants animés.

**Comment by sunny** [comment]
J'aime bien le suffixe "View" et "Template".

J'ai l'impression que oui, par contre, ça serait trop lourd d'avoir toujours cette distinction. Parce que sinon on ferait des `<ParagraphView><ButtonView><TextView>Meh</TextView></ButtonView></ParagraphView>`.

Aussi, ça me paraît bien qu'un composant statique `<Foo />` puisse plus tard décider qu'il a besoin d'un état interne dans certains cas sans avoir à faire de breaking change et changer de nom en façade (il pourra quand même déléguer à un `FooTemplate` par exemple).

**Comment by Ynote** [comment]
Ton dernier point, pour éviter un breaking change, implique donc (aujourd'hui tant qu'on expose tous les composants), qu'il ne faudrait pas suffixer les composants statiques mais les composants qui gèrent un état interne.

**Comment by LanF3usT** [comment]
Pour les petits composants, on pourrait avoir 2 composants dans le même fichier.

```js
export const ProjectCard = props => <ProjectCardView { ...props } />

class ProjectCardView extends … { … }
```

Ca prépare le terrain et permet de ne pas breaking change le composant de rendu.

**Comment by Ynote** [comment]
J'ai l'impression qu'on a déjà eu cette discussion (au moment de `LoanSimulator`). 

Si on choisit d'avoir deux composants comme dans l'exemple ci-dessus `ProjectCard` et `ProjectCardView`, ca suppose qu'on expose `ProjectCardView` mais également en tant que composant statique. Donc, le jour où on veut ajouter un état interne, on appelle le composant qui le gère comment ? Si on l'appelle `ProjectCard`, ça génère un breaking change.

Du coup, j'ai plutôt envie de dire que vu l'état de la lib actuelle, on devrait plutôt suffixer les composants qui gère des états internes plutôt que de suffixer les composants statiques.

**Comment by sunny** [comment]
Pour moi on ne peut pas avoir de dichotomie qui s'applique à tous les composants. Car en façade, sur ce qu'on exporte, on a pas besoin de savoir si l'élément a un état interne ou pas. Pour moi on a réellement deux composants : 

- `ProjectCard` qui gère un seul projet
- `ProjectsCard` qui en gère plusieurs

Si demain on décide qu'une project card doit avoir un état interne parce qu'elle veut gérer un `hover` en JS plutôt qu'en CSS elle devrait pouvoir ajouter un état interne sans que les apps aient à renommer le composant qu'elles utilisent.

Si `ProjectsCard` a un état interne, ça ne regarde que lui. Si, après-demain, il délègue à `<ItemMakers list={ this.props.projects } />` pour gérer cet état et qu'il n'a plus d'état interne, on ne va pas le renommer non plus pour lui retirer son suffixe.

**Comment by Ynote** [comment]
Ok, moi ca me va. Le `s` me semble être assez explicite sur ce que reçoit et gère le composant.

@camilledel, comme tu as soulevé la question, est-ce que ça te semble ok tout ce qu'on s'est dit ?

**Comment by sunny** [comment]
J'ai l'impression que ce qu'on *exporte* ne doit pas pas avoir de suffixe. Mais que si on a un état interne, il faudrait, au sein du même fichier, toujours avoir un composant `*View`.

**Comment by Ynote** [comment]
Je rajoute quand même une nuance. `ProjectSimilarCard` est un composant qui a été pensé pour `SimilarProjectsCard`. Il dispose d'un header qui gère une step et des flèches n'ont pas de sens avec un seul projet.

**Comment by sunny** [comment]
Pas faux.

C'est ça en fait la différence : c'est un composant qui ne fonctionne pas vraiment tout seul. En réalité (si on pouvait décider de ce qu'on exporte aux apps ou pas) j'en aurait fait un composant "interne" utilisé uniquement par `ProjectsCard`.

**Comment by LanF3usT** [comment]
Je pense également que `ProjectSimilarCard` a mal été nommé et devrait devenir par la même occasion `SimilarProjectsCardView`.

**Comment by Ynote** [comment]
En attendant de pouvoir choisir ce qu'on expose, est-ce qu'on décide de faire un breaking change et de nommer `ProjectSimilarCard` en `SimilarProjectsCardView` ?

**Comment by sunny** [comment]
Bof. Je trouve que la distinction n'est pas si forte que ça.

En y réfléchissant on pourrait utiliser `ProjectSimilarCard` tel quel, en affectant aux touches suivant/précédent un `onClick` qui fasse autre chose, sans forcément utiliser `SimilarProjectsCardView`.

**Comment by sunny** [comment]
Je serais plutôt d'avis de le renommer `SimilarProjectCard` et de conserver l'ancien nom, déprécié.

**Comment by camilledel** [comment]
Euh ok ! On en reparle quand vous êtes tous rentrés ?

**Comment by Ynote** [comment]
Nous avions tranché sur le composant `SimilarProjectsCard` avec le dernier commentaire de @sunny. Je vais clôre cette issue qui était spécifique à ce composant et qui nous servira d'historique lorsque nous aurons à nouveau cette question qui se présentera. Et peut-être le noter dans la doc à ce moment-là.
