### ISSUE TITLE
[VOTE] Associer une icône à chaque item de `TagList`

### ISSUE THREAD

**Issue by karineHe** [KissKissBankBank/kitten#811]
Je me retrouve un tantinet coincée à cause d'une TagList un peu aménagée du CIP.

Ce qu'on a aujourd'hui côté composant :
<img width="122" alt="screen shot 2017-08-28 at 18 46 10" src="https://user-images.githubusercontent.com/16986338/29783592-5032fac8-8c21-11e7-9a21-582488f683d0.png">

Ce dont on a besoin côté maquette :
<img width="130" alt="screen shot 2017-08-28 at 18 48 13" src="https://user-images.githubusercontent.com/16986338/29783649-7c6a77ba-8c21-11e7-8265-0089d278dac6.png">

Donc ça resterait une liste mais physiquement affichée avec des séparateurs en plus et des icônes propres à chaque élément. 
La question est donc est-ce qu'il serait plus judicieux de faire un autre composant ou bien de modifier l'actuel composant qui s'en rapproche tout de même énormément...

À VOS VOTES !!!!

**Comment by Morgan-jarry** [comment]
Je pense qu'il y a moyen de réadapter le composant.
On a simplement une liste d'item pouvant contenir, ou non, une icône et un séparateur.

**Comment by Ynote** [comment]
Je vote également pour un ajustement du composant. On ajoute une clé `icon` dans la liste d'item qui gère l'affichage de l'icône et une prop `withSeparator` en plus pour gérer l'affichage d'un séparateur ?

**Comment by karineHe** [comment]
Ça me parait en effet être la meilleure approche... @camilledel ? @sunny ?
(Je vais quand même au passage vérifier ça avec @solenema demain !)

**Comment by sunny** [comment]
J'ai l'impression que ce sont *deux* listes différentes, séparées par un séparateur. Si jamais à droite on a plusieurs tags, est-ce qu'il ne faut pas conserver le comportement de séparer par des `•` les différents tags ?

Ça pourrait même être deux "TagList" différentes, comme par exemple : 

    <TagList tags=[{ title: "Obligation" }] icon=<FileIcon /> />
    |
    <TagList tags=[{ title: "TPE/PME" }, { title: "Green" }] />

Ce qui rendrait un truc genre `[icône] Obligation | [icône] TPE/PME • Green`.

**Comment by karineHe** [comment]
Ah oui on peut le voir comme ça ici. Comme ça ça sera géré dans les 2 dimensions :D

**Comment by camilledel** [comment]
La solution de @sunny me semble la plus simple à mettre en place, ça nous laisse plus de liberté en plus. Et en plus on ajoute rien dans `kitten`, sauf peut-être un exemple.

**Comment by Ynote** [comment]
Si, il faut quand même modifier `Taglist` dans Kitten pour prendre la prop `icon` en compte.

**Comment by sunny** [comment]
Ça implique aussi peut-être de créer un séparateur `|` si du texte simple ne suffit pas.

**Comment by karineHe** [comment]
(Dis-donc t'es pas en vacances toi ! :))

Next step indeed ....

**Comment by camilledel** [comment]
@karine cette issue peut être close ?
