### ISSUE TITLE
[Styleguide] Ajouter une page `About`

### ISSUE THREAD

**Issue by camilledel** [KissKissBankBank/kitten#814]
Cette page explique ce qu'est un styleguide, a quoi il nous sert, ... 

ABOUT
+ A quoi sert kitten 
+ Pourquoi on a besoin du styleguide
+ Pourquoi nous avons décidé de le mettre en Open Source (lien de github)

GUIDELINES
+ Expliquer la création d’un composant (pourquoi on a utilisé tels marges, paddings, …) 
+ Expliquer la cohérence entre les différents formats de button par ex.(schéma)
+ Le choix syntaxique (BEM)

**Comment by camilledel** [comment]
KissKissBankBank, hellomerci et Lendopolis sont 3 plateformes avec une charte graphique différente. Il est devenu indispensable d'unifier l'identité, les composants de chaque plateformes.
Kitten va nous servir à regrouper tous nos composants, à les tester en situation, ...

A quoi sert kitten : 
+ Centraliser tous nos composants
+ Chaque membres de l'équipe Tech  

Pourquoi on besoin du styleguide : 
+ cohérence de la charte graphique entre les 3 plateforms.
+ utilité, clarté et gain de temps d'avoir une unité global cohérente.
+ unification de l'ensemble des composants.

Comment on utilise le styleguide en interne : 
+ 

Pourquoi il est en Open SOurce

**Comment by sunny** [comment]
- `LENDOPOLIS`
- On l'écrit en anglais ?
