### ISSUE TITLE
[Styleguide] Lister les critères à vérifier

### ISSUE THREAD

**Issue by camilledel** [KissKissBankBank/kitten#816]
Lister tous les critères à vérifier avant la release d'un composant.

- [ ] responsive
- [ ] checker avec le produit
- [ ] …

( regarder dans le drive si Mathieu a écrit un doc )
@solenema @qsvr

**Comment by Ynote** [comment]
Je suis sûre que @sunny peut retrouver un début de liste dans ses affaires aussi.

**Comment by sunny** [comment]
Je retrouve des checklists avant le lancement d'un projet (genre [Opquast](https://checklists.opquast.com/oqs-v3/) ) mais pas sur un composant. Donc du haut de ma tête là comme ça j'ajouterais :

- [ ] On a vérifié que le contraste était suffisant important
- [ ] Le composant a des tests automatisés
- [ ] On a testé manuellement sur plusieurs navigateurs

Le souci avec ces checklist de qualité c'est qu'elles peuvent être extrêmement longues. Je penses déjà à mille autres trucs : est ce qu'on a mis des textes alternatifs aux images, est-ce qu'on fait un fallback sur une font générique, est-ce que chaque champ est associé à un label, est-ce que chaque champ texte est associé à une prop, le code est en anglais, il n'y a pas de fautes d'orthographe dans les commentaires, on utilise pas des balises de présentation, on suit notre fashion police, {mille autres bonnes pratiques ici…

**Comment by camilledel** [comment]
Je pense qu'il faut qu'on reste sur des éléments visuels à checker. 
Vérifier si on respecte la maquette, par ex : 
- [ ] On vérifie si c'est un composant cliquable, il doit avoir plusieurs états (hover, disabled, ...)
- [ ] Si on respecte le responsive
- [ ] Si les couleurs, border-size, font-size ... sont respectés.

Mais finalement est ce qu'on devrait pas faire ses checks avant l'intégration du composant ?

cc @sunny, @Ynote

**Comment by Ynote** [comment]
Oui, la liste devrait servir également en amont. On pourrait peut-être commencer par une première liste avec les critères visuels et également une liste pour tout ce qui concerne l'accessibilité (les alts, les fallbacks, les labels dans les formulaires, etc.).

Pour ce qui est du style et les bonnes pratiques de code, ça peut être fait en review de code plutôt ?  J'ai l'impression que l'issue ici concerne plutôt le process au niveau du produit.

**Comment by camilledel** [comment]
Liste qui resense les principaux critères a checker aux niveaux `design`, `dev` et `project manager`. 
http://accessibility.voxmedia.com/?_ga=1.142134770.1909421643.1460637642

**Comment by sunny** [comment]
J'aime bien cette liste.
