### ISSUE TITLE
Scaffold

### ISSUE THREAD

**Issue by Ynote** [KissKissBankBank/kitten#9]
Ca pourrait être utile d'avoir un générateur pour créer les mixins et les fonctions pour un `getting started`. Quelque chose de ce genre : 

``` rb
kitten generate atom MyAtom
```

Output : 

``` sass
/// Here goes your component documentation.
/// Please check http://sassdoc.com/ for more information.
@mixin k-MyAtom {

}
```

Ca genèrerait : 
- le fichier `.scss` ;
- la vue dans le dummy.

Ceci est une idée. À voir pour l'utilité après les prémisses du premier composant.

**Comment by LanF3usT** [comment]
Ayant adopté une intégration en JS, cette issue est obsolète.
