### ISSUE TITLE
Création d'un composant de sélection d'une date

### ISSUE THREAD

**Issue by LanF3usT** [KissKissBankBank/kitten#959]
## Objectif

Actuellement pour gérer une date, nous utilisons `SelectWithState` pour créer les 3 champs. Puis l'application récupère les values de chacun d'entre eux pour avoir la date.

Pour éviter toute cette partie et en attendant d'avoir un date-picker, on pourrait créer un composant `DateSelect`.

## Screenshot

<img width="457" alt="capture d ecran 2017-11-24 a 12 44 22" src="https://user-images.githubusercontent.com/736319/33209356-a7fb7a62-d115-11e7-9635-4d8e7bbc7bde.png">

## Idées

`DateSelect` pourrait prendre des props pour choisir la range de la date, la current value au format `ISO 8601` (`2017-11-24T12:49:10+01:00`), la marge entre les selects, etc.

En sortie il pourrait remonter la date choisie au même format et ensuite c'est à l'application de la gérer (pour les erreurs, pour le push au back, etc.).

**Comment by joachimesque** [comment]
#1732
